const urlCreateCities = "http://localhost:1337/api/cities";
const urlCreateUserLeaderboard = "http://localhost:1337/api/leaderboards";

const data = [
  {
    name: "Amsterdam",
    spanishName: "Amsterdam",
    country: "Netherlands",
    latitude: 52.3702,
    longitude: 4.8952,
    level: 2,
    population: 1272680,
    capital: true,
  },
  {
    name: "Andorra la Vella",
    spanishName: "Andorra",
    country: "Andorra",
    latitude: 42.5063,
    longitude: 1.5218,
    level: 5,
    population: 22256,
    capital: true,
  },
  {
    name: "Athens",
    spanishName: "Atenas",
    country: "Greece",
    latitude: 37.9838,
    longitude: 23.7275,
    level: 2,
    population: 1664046,
    capital: true,
  },
  {
    name: "Belgrade",
    spanishName: "Belgrado",
    country: "Serbia",
    latitude: 44.7866,
    longitude: 20.4489,
    level: 2,
    population: 1180000,
    capital: true,
  },
  {
    name: "Berlin",
    spanishName: "Berlin",
    country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    level: 1,
    population: 3769495,
    capital: true,
  },
  {
    name: "Bern",
    spanishName: "Berna",
    country: "Switzerland",
    latitude: 46.948,
    longitude: 7.4474,
    level: 4,
    population: 134410,
    capital: true,
  },
  {
    name: "Bratislava",
    spanishName: "Bratislava",
    country: "Slovakia",
    latitude: 48.1486,
    longitude: 17.1077,
    level: 4,
    population: 431076,
    capital: true,
  },
  {
    name: "Brussels",
    spanishName: "Bruselas",
    country: "Belgium",
    latitude: 50.8503,
    longitude: 4.3517,
    level: 2,
    population: 1208542,
    capital: true,
  },
  {
    name: "Bucharest",
    spanishName: "Bucarest",
    country: "Romania",
    latitude: 44.4396,
    longitude: 26.0963,
    level: 2,
    population: 1883425,
    capital: true,
  },
  {
    name: "Budapest",
    spanishName: "Budapest",
    country: "Hungary",
    latitude: 47.4979,
    longitude: 19.0402,
    level: 2,
    population: 1752286,
    capital: true,
  },
  {
    name: "Chisinau",
    spanishName: "Chisinau",
    country: "Moldova",
    latitude: 47.0105,
    longitude: 28.8638,
    level: 3,
    population: 673000,
    capital: true,
  },
  {
    name: "Copenhagen",
    spanishName: "Copenhague",
    country: "Denmark",
    latitude: 55.6761,
    longitude: 12.5683,
    level: 2,
    population: 1632340,
    capital: true,
  },
  {
    name: "Dublin",
    spanishName: "Dublin",
    country: "Ireland",
    latitude: 53.3498,
    longitude: -6.2603,
    level: 3,
    population: 553165,
    capital: true,
  },
  {
    name: "Helsinki",
    spanishName: "Helsinki",
    country: "Finland",
    latitude: 60.1699,
    longitude: 24.9384,
    level: 3,
    population: 656250,
    capital: true,
  },
  {
    name: "Kyiv",
    spanishName: "Kiev",
    country: "Ukraine",
    latitude: 50.4501,
    longitude: 30.5234,
    level: 3,
    population: 814922,
    capital: true,
  },
  {
    name: "Lisbon",
    spanishName: "Lisboa",
    country: "Portugal",
    latitude: 38.7223,
    longitude: -9.1393,
    level: 2,
    population: 1547631,
    capital: true,
  },
  {
    name: "Ljubljana",
    spanishName: "Liubliana",
    country: "Slovenia",
    latitude: 46.0569,
    longitude: 14.5058,
    level: 4,
    population: 294218,
    capital: true,
  },
  {
    name: "London",
    spanishName: "Londres",
    country: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    level: 0,
    population: 9176530,
    capital: true,
  },
  {
    name: "Luxembourg",
    spanishName: "Luxemburgo",
    country: "Luxembourg",
    latitude: 49.6116,
    longitude: 6.1319,
    level: 4,
    population: 126818,
    capital: true,
  },
  {
    name: "Madrid",
    spanishName: "Madrid",
    country: "Spain",
    latitude: 40.4168,
    longitude: -3.7038,
    level: 1,
    population: 3266126,
    capital: true,
  },
  {
    name: "Minsk",
    spanishName: "Minsk",
    country: "Belarus",
    latitude: 53.9045,
    longitude: 27.5615,
    level: 2,
    population: 1992800,
    capital: true,
  },
  {
    name: "Monaco",
    country: "Monaco",
    spanishName: "Minsk",
    latitude: 43.7384,
    longitude: 7.4246,
    level: 2,
    population: 1139242,
    capital: true,
  },
  {
    name: "Moscow",
    spanishName: "",
    country: "Russia",
    latitude: 55.7512,
    longitude: 37.6184,
    level: 0,
    population: 12615000,
    capital: true,
  },
  {
    name: "Nicosia",
    spanishName: "",
    country: "Cyprus",
    latitude: 35.1856,
    longitude: 33.3823,
    level: 4,
    population: 311367,
    capital: true,
  },
  {
    name: "Oslo",
    spanishName: "",
    country: "Norway",
    latitude: 59.9139,
    longitude: 10.7522,
    level: 3,
    population: 697549,
    capital: true,
  },
  {
    name: "Paris",
    spanishName: "",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    level: 0,
    population: 18140526,
    capital: true,
  },
  {
    name: "Podgorica",
    spanishName: "",
    country: "Montenegro",
    latitude: 42.4304,
    longitude: 19.2594,
    level: 4,
    population: 136473,
    capital: true,
  },
  {
    name: "Prague",
    spanishName: "",
    country: "Czech Republic",
    latitude: 50.0755,
    longitude: 14.4378,
    level: 2,
    population: 1335968,
    capital: true,
  },
  {
    name: "Reykjavik",
    spanishName: "",
    country: "Iceland",
    latitude: 64.1466,
    longitude: -21.9426,
    level: 2,
    population: 1131136,
    capital: true,
  },
  {
    name: "Riga",
    spanishName: "",
    country: "Latvia",
    latitude: 56.9496,
    longitude: 24.1052,
    level: 3,
    population: 619294,
    capital: true,
  },
  {
    name: "Rome",
    spanishName: "",
    country: "Italy",
    latitude: 41.9028,
    longitude: 12.4964,
    level: 1,
    population: 2857321,
    capital: true,
  },
  {
    name: "San Marino",
    spanishName: "",
    country: "San Marino",
    latitude: 43.9424,
    longitude: 12.4578,
    level: 5,
    population: 4211,
    capital: true,
  },
  {
    name: "Sarajevo",
    spanishName: "",
    country: "Bosnia and Herzegovina",
    latitude: 43.8563,
    longitude: 18.4131,
    level: 4,
    population: 395133,
    capital: true,
  },
  {
    name: "Skopje",
    spanishName: "",
    country: "North Macedonia",
    latitude: 41.9981,
    longitude: 21.4254,
    level: 3,
    population: 552032,
    capital: true,
  },
  {
    name: "Sofia",
    spanishName: "",
    country: "Bulgaria",
    latitude: 42.6977,
    longitude: 23.3219,
    level: 2,
    population: 1236974,
    capital: true,
  },
  {
    name: "Stockholm",
    spanishName: "",
    country: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    level: 3,
    population: 981280,
    capital: true,
  },
  {
    name: "Tallinn",
    spanishName: "",
    country: "Estonia",
    latitude: 59.437,
    longitude: 24.7536,
    level: 4,
    population: 439344,
    capital: true,
  },
  {
    name: "Tirana",
    spanishName: "",
    country: "Albania",
    latitude: 41.3275,
    longitude: 19.8187,
    level: 3,
    population: 622409,
    capital: true,
  },
  {
    name: "Vaduz",
    spanishName: "",
    country: "Liechtenstein",
    latitude: 47.141,
    longitude: 9.5215,
    level: 5,
    population: 5500,
    capital: true,
  },
  {
    name: "Valletta",
    spanishName: "",
    country: "Malta",
    latitude: 35.8989,
    longitude: 14.5146,
    level: 4,
    population: 383404,
    capital: true,
  },
  {
    name: "Vienna",
    spanishName: "",
    country: "Austria",
    latitude: 48.2082,
    longitude: 16.3738,
    level: 0,
    population: 11920532,
    capital: true,
  },
  {
    name: "Vilnius",
    spanishName: "",
    country: "Lithuania",
    latitude: 54.6872,
    longitude: 25.2797,
    level: 3,
    population: 574147,
    capital: true,
  },
  {
    name: "Warsaw",
    spanishName: "",
    country: "Poland",
    latitude: 52.2297,
    longitude: 21.0122,
    level: 2,
    population: 1780648,
    capital: true,
  },
  {
    name: "Zagreb",
    spanishName: "",
    country: "Croatia",
    latitude: 45.815,
    longitude: 15.9819,
    level: 3,
    population: 804200,
    capital: true,
  },
  {
    name: "Buenos Aires",
    spanishName: "Buenos Aires",
    country: "Argentina",
    latitude: -34.61,
    longitude: -58.38,
    population: 2891000,
    level: 1,
    capital: true,
  },
  {
    name: "La Paz",
    spanishName: "La Paz",
    country: "Bolivia",
    latitude: -16.5,
    longitude: -68.15,
    population: 812799,
    level: 3,
    capital: true,
  },
  {
    name: "Brasília",
    spanishName: "Brasilia",
    country: "Brazil",
    latitude: -15.78,
    longitude: -47.93,
    population: 3015268,
    level: 1,
    capital: true,
  },
  {
    name: "Santiago",
    spanishName: "Santiago",
    country: "Chile",
    latitude: -33.45,
    longitude: -70.67,
    population: 5031477,
    level: 0,
    capital: true,
  },
  {
    name: "Bogotá",
    spanishName: "Bogota",
    country: "Colombia",
    latitude: 4.61,
    longitude: -74.08,
    population: 7878783,
    level: 0,
    capital: true,
  },
  {
    name: "Quito",
    spanishName: "Quito",
    country: "Ecuador",
    latitude: -0.23,
    longitude: -78.52,
    population: 2762444,
    level: 1,
    capital: true,
  },
  {
    name: "Asunción",
    spanishName: "Asuncion",
    country: "Paraguay",
    latitude: -25.26,
    longitude: -57.64,
    population: 525294,
    level: 3,
    capital: true,
  },
  {
    name: "Lima",
    spanishName: "Lima",
    country: "Peru",
    latitude: -12.04,
    longitude: -77.03,
    population: 9479976,
    level: 0,
    capital: true,
  },
  {
    name: "Montevideo",
    spanishName: "Montevideo",
    country: "Uruguay",
    latitude: -34.9,
    longitude: -56.19,
    population: 1319108,
    level: 2,
    capital: true,
  },
  {
    name: "Caracas",
    spanishName: "Caracas",
    country: "Venezuela",
    latitude: 10.48,
    longitude: -66.9,
    population: 1943901,
    level: 2,
    capital: true,
  },
];

const createCapitals = () => {
  data.map((city) => {
    city.latitude = "" + city.latitude;
    city.longitude = "" + city.longitude;
    fetch(urlCreateCities, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ data: city }),
    })
      .then((response) => {
        console.log(response);
        return response.json();
      })
      .then((result) => {
        console.log("POST request successful:", result);
      })
      .catch((error) => {
        console.error("Error making POST request:", error);
      });
    return true;
  });
};

const submitUser = async (username, streak) => {
  const user = { username: username, streak: streak };
  let finalResponse;
  finalResponse = await fetch(urlCreateUserLeaderboard, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ data: user }),
  })
    .then((response) => {
      console.log(response);
      return response.json();
    })
    .then((result) => {
      console.log("POST request successful:", result);
      return result;
    })
    .catch((error) => {
      console.error("Error making POST request:", error);
      return error;
    });
  return finalResponse;
};

const createMethods = {
  createCapitals,
  submitUser,
};

export default createMethods;
