
const dataEmoji = [
    { city: "Amsterdam", country: "Netherlands", emoji: "🇳🇱" },
    { city: "Andorra la Vella", country: "Andorra", emoji: "🇦🇩" },
    { city: "Athens", country: "Greece", emoji: "🇬🇷" },
    { city: "Belgrade", country: "Serbia", emoji: "🇷🇸" },
    { city: "Berlin", country: "Germany", emoji: "🇩🇪" },
    { city: "Bern", country: "Switzerland", emoji: "🇨🇭" },
    { city: "Bratislava", country: "Slovakia", emoji: "🇸🇰" },
    { city: "Brussels", country: "Belgium", emoji: "🇧🇪" },
    { city: "Bucharest", country: "Romania", emoji: "🇷🇴" },
    { city: "Budapest", country: "Hungary", emoji: "🇭🇺" },
    { city: "Chisinau", country: "Moldova", emoji: "🇲🇩" },
    { city: "Copenhagen", country: "Denmark", emoji: "🇩🇰" },
    { city: "Dublin", country: "Ireland", emoji: "🇮🇪" },
    { city: "Helsinki", country: "Finland", emoji: "🇫🇮" },
    { city: "Kyiv", country: "Ukraine", emoji: "🇺🇦" },
    { city: "Lisbon", country: "Portugal", emoji: "🇵🇹" },
    { city: "Ljubljana", country: "Slovenia", emoji: "🇸🇮" },
    { city: "London", country: "United Kingdom", emoji: "🇬🇧" },
    { city: "Luxembourg City", country: "Luxembourg", emoji: "🇱🇺" },
    { city: "Madrid", country: "Spain", emoji: "🇪🇸" },
    { city: "Minsk", country: "Belarus", emoji: "🇧🇾" },
    { city: "Monaco", country: "Monaco", emoji: "🇲🇨" },
    { city: "Moscow", country: "Russia", emoji: "🇷🇺" },
    { city: "Nicosia", country: "Cyprus", emoji: "🇨🇾" },
    { city: "Oslo", country: "Norway", emoji: "🇳🇴" },
    { city: "Paris", country: "France", emoji: "🇫🇷" },
    { city: "Podgorica", country: "Montenegro", emoji: "🇲🇪" },
    { city: "Prague", country: "Czech Republic", emoji: "🇨🇿" },
    { city: "Reykjavik", country: "Iceland", emoji: "🇮🇸" },
    { city: "Riga", country: "Latvia", emoji: "🇱🇻" },
    { city: "Rome", country: "Italy", emoji: "🇮🇹" },
    { city: "San Marino", country: "San Marino", emoji: "🇸🇲" },
    { city: "Sarajevo", country: "Bosnia and Herzegovina", emoji: "🇧🇦" },
    { city: "Skopje", country: "North Macedonia", emoji: "🇲🇰" },
    { city: "Sofia", country: "Bulgaria", emoji: "🇧🇬" },
    { city: "Stockholm", country: "Sweden", emoji: "🇸🇪" },
    { city: "Tallinn", country: "Estonia", emoji: "🇪🇪" },
    { city: "Tirana", country: "Albania", emoji: "🇦🇱" },
    { city: "Vaduz", country: "Liechtenstein", emoji: "🇱🇮" },
    { city: "Valletta", country: "Malta", emoji: "🇲🇹" },
    { city: "Vienna", country: "Austria", emoji: "🇦🇹" },
    { city: "Vilnius", country: "Lithuania", emoji: "🇱🇹" },
    { city: "Warsaw", country: "Poland", emoji: "🇵🇱" },
    { city: "Zagreb", country: "Croatia", emoji: "🇭🇷" },
    { city: "Buenos Aires", country: "Argentina", emoji: "🇦🇷" },
    { city: "La Paz", country: "Bolivia", emoji: "🇧🇴" },
    { city: "Brasilia", country: "Brazil", emoji: "🇧🇷" },
    { city: "Santiago", country: "Chile", emoji: "🇨🇱" },
    { city: "Bogota", country: "Colombia", emoji: "🇨🇴" },
    { city: "Quito", country: "Ecuador", emoji: "🇪🇨" },
    { city: "Asuncion", country: "Paraguay", emoji: "🇵🇾" },
    { city: "Lima", country: "Peru", emoji: "🇵🇪" },
    { city: "Montevideo", country: "Uruguay", emoji: "🇺🇾" },
    { city: "Caracas", country: "Venezuela", emoji: "🇻🇪" },
]